Repository libdebug/libdebug, pull requests merged in 2025-02, with the labels that each got.

#151 Migrate from CFFI to Nanobind
  .gitignore
  CMakeLists.txt
  libdebug/architectures/aarch64/aarch64_ptrace_register_holder.py
  libdebug/architectures/amd64/amd64_ptrace_register_holder.py
  libdebug/architectures/i386/i386_ptrace_register_holder.py
  libdebug/cffi/debug_sym_cffi_build.py
  libdebug/cffi/debug_sym_cffi_build_legacy.py
  libdebug/cffi/debug_sym_cffi_source.c
  libdebug/cffi/debug_sym_cffi_source_legacy.c
  libdebug/cffi/personality_cffi_build.py
  libdebug/cffi/ptrace_cffi_build.py
  libdebug/cffi/ptrace_cffi_source.c
  libdebug/data/terminals.py
  libdebug/debugger/internal_debugger.py
  libdebug/native/__init__.py
  libdebug/native/linux_interface.cpp
  libdebug/native/symbols/__init__.py
  libdebug/native/symbols/debug_sym_parser.cpp
  libdebug/native/symbols/debug_sym_parser.h
  libdebug/native/symbols/debug_sym_parser_legacy.cpp
  libdebug/native/symbols/debug_sym_parser_new.cpp
  libdebug/ptrace/native/__init__.py
  libdebug/ptrace/native/aarch64/__init__.py
  libdebug/ptrace/native/aarch64/aarch64_ptrace.cpp
  libdebug/ptrace/native/aarch64/aarch64_ptrace.h
  libdebug/ptrace/native/amd64/__init__.py
  libdebug/ptrace/native/amd64/amd64_ptrace.cpp
  libdebug/ptrace/native/amd64/amd64_ptrace.h
  libdebug/ptrace/native/i386/__init__.py
  libdebug/ptrace/native/i386/i386_ptrace.cpp
  libdebug/ptrace/native/i386/i386_ptrace.h
  libdebug/ptrace/native/libdebug_ptrace_base.h
  libdebug/ptrace/native/libdebug_ptrace_binding.cpp
  libdebug/ptrace/native/libdebug_ptrace_interface.h
  libdebug/ptrace/native/shared/__init__.py
  libdebug/ptrace/native/shared/x86_autogenerate_xsave_layout.c
  libdebug/ptrace/native/shared/x86_ptrace.cpp
  libdebug/ptrace/native/shared/x86_ptrace.h
  libdebug/ptrace/ptrace_interface.py
  libdebug/ptrace/ptrace_status_handler.py
  libdebug/utils/elf_utils.py
  libdebug/utils/process_utils.py
  pyproject.toml
  setup.py
  test/other_tests/gdb_migration_test.py
  test/scripts/antidebug_escaping_test.py
  test/scripts/atexit_handler_test.py
  test/scripts/auto_waiting_test.py
  test/scripts/callback_test.py
  test/scripts/death_test.py
  test/scripts/memory_test.py
  test/scripts/pprint_syscalls_test.py
Labels: enhancement

#187 Add some more subclasses and abstract classes to the codebase
  libdebug/architectures/aarch64/aarch64_thread_context.py
  libdebug/architectures/amd64/amd64_thread_context.py
  libdebug/architectures/amd64/compat/i386_over_amd64_thread_context.py
  libdebug/architectures/i386/i386_thread_context.py
  libdebug/architectures/thread_context_helper.py
  libdebug/ptrace/ptrace_interface.py
  libdebug/state/thread_context.py
Labels: bug

#167 Added missing documentation on `redirect_pipes=False`
  docs/basics/running_an_executable.md
Labels: documentation
